base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('home/', views.home, name="homepage"),
    path('', views.homepage, name="home"),
    

    path('room/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),

    path('create-room/', views.createRoom, name="create-room"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User 

# Create your models here.

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete = models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete = models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank = True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True) 
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str_(self):
        return self.name
    

class Message(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete = models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.models import User 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from .models import Room, Topic, Message
from .forms import RoomForm

# Create your views here.

# rooms = [
#     {'id':1, 'name': 'Lets learn python!'},
#     {'id':2, 'name': 'Design with me'},
#     {'id':3, 'name': 'Frontend developers'},
# ]

def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, "User does not exist.")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Username or Password does not exits.")

    context={'page':page}
    return render(request, 'base/login_register.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:
            messages.error(request,'An error occurred during registration.')

    return render(request,'base/login_register.html',{'form':form})

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
                            Q(topic__name__icontains=q) |
                            Q(name__icontains = q) |
                            Q(description__contains = q)
            )

    topics = Topic.objects.all()
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains = q))

    context = {'rooms':rooms, 'topics':topics, 'room_count':room_count, 'room_messages':room_messages}
    return render(request, 'base/home.html',context)

def homepage(request):
    return render(request, 'base/homepage.html')
    

def room(request, pk):
    room = Room.objects.get(id=pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user = request.user,
            room = room,
            body = request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room', pk = room.id)
    context = {'room':room, 'room_messages':room_messages, 'participants':participants}
    return render(request, 'base/room.html', context)


def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user':user, 'rooms':rooms, 'room_messages':room_messages,'topics':topics}
    return render(request, 'base/profile.html', context)

@login_required(login_url='login')
def createRoom(request):
    form = RoomForm()

    if request.method == 'POST':
        form = RoomForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.host = request.user
            room.save()
            return redirect('home')
        
    context = {'form' : form}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)

    if request.user != room.host:
        return HttpResponse('You are not allowed here!!')

    if request.method == 'POST':
        form = RoomForm(request.POST, instance=room)
        if form.is_valid():
            form.save()
            return redirect('home')

    context = {'form':form}
    return render(request, 'base/room_form.html', context)


@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id = pk)

    if request.user != room.host:
        return HttpResponse('You are not allowed here!!')
    
    if request.method == 'POST':
        room.delete()
        return redirect('homepage')

    return render(request, 'base/delete.html', {'obj':room})


@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id = pk)

    if request.user != message.user:
        return HttpResponse('You are not allowed here!!')
    
    if request.method == 'POST':
        message.delete()
        return redirect('homepage')

    return render(request, 'base/delete.html', {'obj':message})

base/templates/base/activity_component.html
{% load static %}

<div class="right-col-2">
    <h2>RECENT ACTIVITIES</h2>
    <hr>

    {% for message in room_messages %}

    <div class="activities">
        <div class="act-1">
            <div class="prof">
                <img src="{% static '/images/ellipse2.png' %}" alt="">
            </div>
            <div class="prof-2">
                <b><p><a href="{% url 'user-profile' message.user.id %}" style="text-decoration: none;
                    color: #fff;">@{{ message.user }}</a></p></b>
                <p>{{ message.created|timesince }} ago</p>
                <p>replied to post "<a href="{% url 'room' message.room.id %}" style="text-decoration: none;
                color: #fff;">{{ message.room.name }}</a>"</p>
            </div>
        </div>
        <div class="act-2">
            <p>{{ message.body }}</p>
        </div>
        {% if request.user == message.user %}
        <a href="{% url 'delete-message' message.id %}" style="text-decoration: none;
        color: #fff; font-family: 'Laila',sans-serif;">Delete</a>
        {% endif %}
    </div>

    {% endfor %}

    </div>
</div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<style>
    .del {
    background: #162b3f;
    width: 27%;
    color: #fff;
    text-decoration: none;
    height: 116px;
    display: flex;
    border-radius: 25px;
    gap: 7px;
    flex-direction: column;
    align-items: center;
    box-shadow: rgba(0, 0, 0, 0.19) 0px 10px 20px, rgba(0, 0, 0, 0.23) 0px 6px 6px;
    justify-content: center;
    font-family: "Laila", serif;
}

    .del a {
    color: #fff;
}

input[type="submit"] {
    width: 80px;
    height: 27px;
    border-radius: 25px;
    background: #fff;
    border: none;
}

</style>

<form method="post" action="" style="
    position: absolute;
    display: flex;
    top: 97px;
    /* background: #4682a9; */
    width: 100%;
    height: auto;
    flex-direction: column;
    align-items: center;">
    {% csrf_token %}
    <div class="del">
    <p>Are you sure you want to delete "{{obj.name}}"?</p>
    <a href="{{ request.META.HTTP_REFERER }}">Go back</a>

    <input type="submit" value="Confirm" />

</div>
</form>

{% endblock content %}

base/templates/base/feed_component.html
{% load static %}

{% for room in rooms %}

<div class="middle-col-2">
    <div class="panel-1">
        <div class="panel-left">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <p style="font-size: 19px;">Host <a href="{% url 'user-profile' room.host.id %}" style="text-decoration: none;
            color: #fff;"> @{{ room.host.username }} </a></p>
        </div>
        <p>{{ room.created|timesince }} ago</p>
    </div>

    <div class="panel-2">
        <div class="title">

            <a href="{% url 'room' room.id %}" style="text-decoration: none;"><h2>{{ room.name }}</h2></a>
        
        </div>
        <div class="partic">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
            
        </div>
    </div>

    <hr>

    <div class="panel-3">
        <div class="panLeft">
            <i class="fa fa-users" aria-hidden="true"></i><p>{{ room.participants.all.count }} Joined</p>
        </div>
        <p>{{ room.topic.name }}</p>
    </div>
</div>

{% endfor %}

base/templates/base/home.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

      <div class="container">
        <img src="{% static 'images/vector.png' %}" alt="" srcset="" style=" 
        left: 7%;
        position: absolute;
        top: 44%;
        width: 66px;
        transform: rotate(302deg);">
        <img src="{% static 'images/vector.png' %}" alt="" srcset="" style=" 
       left: 12%;
        position: absolute;
        top: 38%;
        width: 49px;
        transform: rotate(302deg);">
        <img src="{% static 'images/vector.png' %}" alt="" srcset="" style=" 
        left: 73%;
        position: absolute;
        top: 8%;
        width: 66px;
        transform: rotate(356deg);">
        <img src="{% static 'images/vector.png' %}" alt="" srcset="" style=" 
        left: 19%;
        position: absolute;
        top: 78%;
        width: 89px;
        transform: rotate(242deg);">

        {% include 'base/topic_component.html' %}
       

        <div class="middle">
            <div class="middle-col-1">
                <div class="middle-row1">
                    <h2>ROOMS</h2>
                    <p>{{ room_count }} Rooms Available</p>
                </div>
                <a href="{% url 'create-room' %}" style="text-decoration: none; 
                color: #fff; cursor: pointer;"><button>Create Room</button></a>
            </div>
            <p style="color: #4682A9;font-family: 'Laila',sans-serif;font-size: 20px;padding: 10px 0px;font-weight: bold;">All Rooms</p>
            
            <!-- content  -->


            {% include 'base/feed_component.html' %}

    
        </div>

        
        <div class="right">
            <div class="right-col-1">
                <h2>TOP HOSTS</h2>
                <hr>
                <div class="followers">
                    <div class="rows-2">
                        <div class="profile">
                            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
                            <p>Erik Davis</p>
                        </div>
                        <button>Follow</button>
                    </div>

                    <div class="rows-2">
                        <div class="profile">
                            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
                            <p>Tim</p>
                        </div>
                        <button>Follow</button>
                    </div>

                    <div class="rows-2">
                        <div class="profile">
                            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
                            <p>John</p>
                        </div>
                        <button>Follow</button>
                    </div>

                    <div class="rows-2">
                        <div class="profile">
                            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
                            <p>Jenny Wilson</p>
                        </div>
                        <button>Follow</button>
                    </div>

                    <div class="rows-2">
                        <div class="profile">
                            <img src="{% static 'images/ellipse2.png' %}" alt="" srcset="">
                            <p>Darlene Robertson</p>
                        </div>
                        <button>Follow</button>
                    </div>
                </div>
            </div>


            {% include 'base/activity_component.html' %}

                
                

        

      </div>

      {% endblock %}

base/templates/base/home_old.html
{% extends "main.html" %}

{% block content  %}


<style>
    .home-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<div class="home-container">

    <div>
        {% include 'base/topic_component.html' %}
    </div>

    <div>

        <h5>{{ room_count }} rooms available</h5>

        <a href="{% url 'create-room' %}">Create Room</a>

        <div>
            {% include 'base/feed_component.html' %}
        </div>

    </div>

    <div>
        {% include 'base/activity_component.html' %}
    </div>

</div>

{% endblock  %}

base/templates/base/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PlanX</title>
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

  <header>
    <div class="logo-name"><a href="#"><img src="{% static 'images/Logo.png' %}" class="logo"></a>
      <p>PlanX</p>
    </div>
    <div class="navbar" id="navbar">
      <ul class="nav-links">
          <!-- <li><a href="holiday.html">Holidays</a></li> -->
          <!-- <li><a href="hotels.html">Hotels</a></li> -->
          <li><a href="#">Community</a></li>
          <li><a href="#">Support</a></li>
          <li><a href="#">Blog</a></li>
          <li><a href="#abt">About Us</a></li>
      </ul>
      <a href="{% url 'login' %}" class="login-btn"><i class="fa fa-user"></i></a>
      
      <a href="javascript:void(0);" class="icon" onclick="myFunction()">
          <i class="fa fa-bars"></i>
      </a>
    </div>
  </header>

  <div class="container" id="home">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="width: 76px; position: absolute;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="width: 36px; position: absolute; top: 15%; left: 112px;">

    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 54px;
    left: 78%;
    top: 73%;
    transform: rotate(329deg);
    position: absolute;">
    <img src="images/vector.png" alt="" class="vector" style="    
    width: 64px;
    position: absolute;
    top: 36%;
    left: 1278px;">


    <div class="buttonCont">
      <a href="{% url 'homepage' %}"><button class="button-1">Join</button></a>
      <a href="{% url 'create-room' %}"><button class="button-2">Create</button></a>
  </div>
    <div class="img-container">
      <div class="obj"><img src="{% static 'images/vector1.png' %}"></div>
      <img src="{% static 'images/studyAnimals.png' %}" alt="studyAnimals" class="img-cont">
    </div>
    <div class="desc">
      <h1>Plan, Discuss, Connect...</h1>
      <p>Your digital hub for lively discussions and collaborative planning. <br>
        Join us to share ideas, exchange perspectives, and bring your plans to life.</p>
        <a href="{% url 'homepage' %}"><button class="button">Know More</button></a>
    </div>
  </div>
  
  <div class="container">


    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 98px;
    left: 7%;
    top: 22%;
    transform: rotate(329deg);
    position: absolute;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 32px;
    position: absolute;
    top: 14%;
    left: 221px;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 40px;
    position: absolute;
    top: 3%;
    transform: rotate(343deg);
    left: 78px;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 64px;
    position: absolute;
    top: 68%;
    transform: rotate(343deg);
    left: 1092px;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 35px;
    position: absolute;
    top: 77%;
    transform: rotate(293deg);
    left: 1043px;">

    <div class="desc-2">
      <h1>Join or Create Discussion Rooms</h1>
      <p>Encourage users to join existing discussion rooms or <br>create their own on topics of interest.</p>
        <button class="white-button">Join</button>
        <button class="button">Create</button> 
    </div>
    <div class="img-container-2">
      <div class="obj"><img src="{% static 'images/vector2.png' %}"></div>
      <div class="obj-2"><img src="{% static 'images/vector3.png' %}"></div>
      <img src="{% static 'images/penguinPhone.png' %}" alt="studyAnimals" class="img-cont">
      <img src="{% static 'images/Penguineggs.png' %}" alt="studyAnimals" class="img-cont-2">
    </div>
    
  </div>

  <div class="container-2">

    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 68px;
    left: 7%;
    top: -16%;
    transform: rotate(329deg);
    position: absolute;">
    <img src="{% static 'images/vector.png' %}" alt="" class="vector" style="    
    width: 92px;
    position: absolute;
    top: -31%;
    left: 180px;">

    <div class="desc-2">
      <h1>CONNECT INSTANTLY FOR <br>COLLABORATIVE MOMENTS</h1>
      <p>Experience swift, lag-free text communication that brings <br> you together effortlessly. Share ideas, collaborate, and <br>engage in real-time discussions seamlessly.</p>
      <img src="{% static 'images/pandaBino.png' %}" alt="">
      <button class="button">Know More</button>
    </div>
    <div class="img-container-2">
      <div class="obj">
        <img src="{% static 'images/vector2.png' %}">
      </div>
      <img src="{% static 'images/PandaTree.png' %}" alt="studyAnimals" class="img-cont">
    </div>
    
  </div>

  <div class="dark-container">
    <img src="{% static 'images/penguinSpace.png' %}" alt="" class="img-1">
    <h1>Hear What Our Users Have to Say</h1>
    <button class="button">More</button>
    <div class="cards-container">
      <div class="cards">
        <div class="profile">
          <img src="{% static 'images/ellipse2.png' %}" alt="">
        </div>
        <div class="flex-icon">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
      </div>
        <div class="p-2">
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore, laboriosam. Cumque atque nihil, quidem omnis asperiores totam ex quam minima!</p>
        </div>
      </div>

      <div class="cards">
        <div class="profile">
          <img src="{% static 'images/ellipse2 (1).png' %}" alt="">
        </div>
        <div class="flex-icon">
        <img src="{% static 'images/star-solid.png' %}g" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
      </div>
        <div class="p-2">
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore, laboriosam. Cumque atque nihil, quidem omnis asperiores totam ex quam minima!</p>
        </div>
      </div>

      <div class="cards">
        <div class="profile">
          <img src="{% static 'images/ellipse2 (2).png' %}" alt="">
        </div>
        <div class="flex-icon">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
        <img src="{% static 'images/star-solid.png' %}" alt="">
      </div>
        <div class="p-2">
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Tempore, laboriosam. Cumque atque nihil, quidem omnis asperiores totam ex quam minima!</p>
        </div>
      </div>
      
    </div>
  </div>

  <footer class="footer-cont" id="abt">
      <div class="footer-up">
        <div class="left">
          <h2>English</h2>
          <div class="icons-footer">
            <i class="fa fa-twitter" aria-hidden="true"></i>
            <i class="fa fa-instagram" aria-hidden="true"></i>
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
            <i class="fa fa-youtube-play" aria-hidden="true"></i>
          </div>
        </div>
        <div class="right">
          <div class="row-1">
            <span>Resources</span>
            <p>College</p>
            <p>Support</p>
            <p>Safety</p>
            <p>Blog</p>
            <p>Feedback</p>
            <p>Creators</p>
            <p>Community</p>
            <p>Developers</p>
            <p>Gaming</p>
          </div>

          <div class="row-2">
            <span>Policies</span>
            <p>Terms</p>
            <p>Privacy</p>
            <p>Cookie Settings</p>
            <p>Guidelines</p>
            <p>Acknowledgements</p>
            <p>License</p>
            <p>Company Information</p>
          </div>
        </div>
      </div>
      <hr>
      <div class="footer-down">
        <div class="logo-footer"><a href="#home"><img src="{% static 'images/Logo.png' %}" class="logo"></a>
          <p>PlanX</p>
        </div>
        <button class="white-button">SignUp</button>
      </div>
  </footer>
      <!-- external js file  -->
      <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container{
        display: flex;
        /* grid-template-columns: 1fr 3fr 1fr; */
        top: 77%;
        
    }
</style>

<h1>{{ user.username }}</h1>

<div class="profile-container">
   
        {% include 'base/topic_component.html' %}
    

    <div style="
    display: flex;
    flex-direction: column;
    width: 52%;
    margin-right: 29px;
    margin-top: 45px;">
        {% include 'base/feed_component.html' %}
    </div>

    
        {% include 'base/activity_component.html' %}
    
</div>

{% endblock content %}

base/templates/base/room_form.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
      
      <link rel="stylesheet" href="{% static 'styles/room_form.css' %}">
      <div class="container">
        <img src="{% static '/images/vector.png' %}" alt="" srcset="" style=" 
        left: 7%;
        position: absolute;
        top: 44%;
        width: 66px;
        transform: rotate(302deg);">
        <img src="{% static '/images/vector.png' %}" alt="" srcset="" style=" 
       left: 12%;
        position: absolute;
        top: 38%;
        width: 49px;
        transform: rotate(302deg);">
        <img src="{% static '/images/vector.png' %}" alt="" srcset="" style=" 
        left: 73%;
        position: absolute;
        top: 8%;
        width: 66px;
        transform: rotate(356deg);">
        <img src="{% static '/images/vector.png' %}" alt="" srcset="" style=" 
        left: 19%;
        position: absolute;
        top: 78%;
        width: 89px;
        transform: rotate(242deg);">

        {% comment %} <img src="{% static '/images/pengui.png' %}" alt="" srcset="" class="peng"> {% endcomment %}
        <div class="cont">
          <h1 class="dup">Create Room</h1>
          <h1 class="dup-1">Create Room</h1>

          <form method="post" action="" class="room_form">
            {% csrf_token %}
              <div class="row">
                  <p>Room Name</p>
                  <input type="text" name="name" placeholder="Eg. Mastering Python + Django"/>
              </div>

              <div class="row">
                  <p>Topic</p>
                  <select name="topic" required="" id="id_topic">
                    <option value="" selected="">---------</option>
                  
                    <option value="1">Python</option>
                  
                    <option value="2">Django</option>
                  
                    <option value="3">Web Development</option>
                  
                    <option value="4">JavaScript</option>
                  
                  </select>
                  {% comment %} <input type="text" /> {% endcomment %}
              </div>

              <div class="row">
                  <p>About</p>
                  <input type="text" name="description" placeholder="Write about your Room" class="textView"/>
              </div>

              <div class="submitButton">
                  {% comment %} <input type="reset" value="Cancel" id="">  {% endcomment %}
                  <input type="submit" value="Create Room" id="">
              </div>
          </form>

        </div>
      </div>

      {% endblock content %}

base/templates/base/room_form_old.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="submit" />
    </form>
</div>

{% endblock content %}

base/templates/base/room_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .room-container{
        display: grid;
        grid-template-columns: 3fr 1fr;
    }
</style>

<div class="room-container">

    <div>
        <h1>{{ room.name }}</h1>

        <p>{{ room.description }}</p>

        <div class="commment-wrapper">
            <h3>Conversation</h3>
            <hr>

            {% for message in room_messages %}

            <div>
                {% if request.user == message.user %}
                <a href="{% url 'delete-message' message.id %}">Delete</a>
                {% endif %}
                <small>@{{ message.user }} {{ message.created|timesince }} ago </small>
                <p>{{ message.body }}</p>
                <hr>
            </div>

            {% endfor %}
        </div>


        {% if request.user.is_authenticated %}
        <div class="comment-form">
            <form method="POST" action="">
                {% csrf_token %}
                <input type="text" name="body" placeholder="Write your message here..." />
            </form>
        </div>
        {% endif %}
    </div>

    <div>
        <h3>Participants</h3>
        <hr>
        {% for user in participants %}
            <p>@{{ user.username }}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

base/templates/base/topic_component.html
 
        <div class="left">
            <div class="left-col-1">
                <h2>BROWSE TOPICS</h2>
            </div>

            <div class="left-col-2">
                <div class="rows">
                    <span style="color: #4682A9;"><p> All</p></span>
                    <a href="{% url 'homepage' %}" style="text-decoration: none;">
                        <button>{{ topics.count }}</button>
                    </a>
                </div>

                {% for topic in topics %}

                <div class="rows">
                    <p>{{topic.name}} <span>( {{topic.room_set.all.count}} )</span></p>
                    <a href="{% url 'homepage' %}?q={{topic.name}}" style="text-decoration: none; color: #fff;">
                        <button> Follow</button>
                    </a>
                </div>

                {% endfor %}
            </div>
        </div>